services:
  api:
    build:
      context: backend/.
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - backend/.env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend
  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - PUBLIC_API_URL=http://localhost:8080/api
